/**
 * Created by tamleminh on 19/04/2017.
 */
const data = {
  r: 30,
  code: '',
  cocode: 884437981,
  src: '',
  format: 1,
  width: 300,
  type: 'boxadx',
  l: '',
  items: [{
    image: '\/\/adi.admicro.vn\/adt\/adn\/2017\/01\/e1-adx587c7fb4087c3.jpg',
    pr: 6918136225,
    color: '0059a9',
    link3rd: '',
    link: 'http:\/\/benhdaulung.vn\/chia-se\/cuu-tinh-nhung-cot-song-dang-thuong-nguyen-xuan-dien.html?utm_source=Adx_admicro&utm_campaign=cotthoaivuong&utm_medium=cuu-tinh-nhung-cot-song-dang-thuong&utm_content=[admdomain]',
    sologan: '',
    title: 'Cứu tinh những cột sống đáng thương',
    r: 50,
    cpa: 1,
    isview: '',
    domain: 'benhdaulung.vn',
    titlebox: 'TƯ VẤN BỆNH XƯƠNG KHỚP HAY GẶP',
    bid: 68213,
    brand: '',
    desc: '"Tôi cứ xách 2 xô nước nặng là lưng lại bị đau. Đi bộ 200m là phải ngồi nghỉ ngơi và đấm lưng"',
    cid: 21534,
  }, {
    image: '\/\/adi.admicro.vn\/adt\/adn\/2017\/01\/e2-adx587c9e85a4a8c.jpg',
    pr: 6920046415,
    color: '0059a9',
    link3rd: '',
    link: 'http:\/\/benhdaulung.vn\/chia-se\/bi-quyet-day-lui-benh-thoat-vi-dia-dem.html?utm_source=Adx_admicro&utm_campaign=cotthoaivuong&utm_medium=bi-quyet-day-lui-benh-thoat-vi-dia-dem&utm_content=[admdomain]',
    sologan: '',
    title: 'Bí quyết đẩy lùi bệnh thoát vị đĩa đệm',
    r: 50,
    cpa: 1,
    isview: '',
    domain: 'benhdaulung.vn',
    titlebox: 'TƯ VẤN BỆNH XƯƠNG KHỚP HAY GẶP',
    bid: 68232,
    brand: '',
    desc: 'Kinh nghiệm hữu ích cho nhiều người',
    cid: 21534,
  }, {
    image: '\/\/adi.admicro.vn\/adt\/adn\/2017\/01\/e3-adx587c9ee75fc08.jpg',
    pr: 6920156425,
    color: '0059a9',
    link3rd: '',
    link: 'http:\/\/benhdaulung.vn\/chia-se\/giam-90-thoai-hoa-cot-song-cova-vac-bao-lua-nang-50kg-chi-sau-3-thang.html?utm_source=Adx_admicro&utm_campaign=cotthoaivuong&utm_medium=giam-90%-thoai-hoa-cot-song-co-sau-3-thang&utm_content=[admdomain]',
    sologan: '',
    title: 'Giảm 90% thoái hóa cột sống cổ sau 3 tháng',
    r: 50,
    cpa: 1,
    isview: '',
    domain: 'benhdaulung.vn',
    titlebox: 'TƯ VẤN BỆNH XƯƠNG KHỚP HAY GẶP',
    bid: 68233,
    brand: '',
    desc: 'Hai năm ròng rã chiến đấu với căn bệnh thoái hóa đốt sống cổ',
    cid: 21534,
  }, {
    image: '\/\/adi.admicro.vn\/adt\/adn\/2017\/01\/e4-adx587ca140ae325.jpg',
    pr: 6920266435,
    color: '0059a9',
    link3rd: '',
    link: 'http:\/\/benhdaulung.vn\/chia-se\/uong-cot-thoai-vuong-giam-han-thoat-vi-dot-song-co-toi-mung-lam.html?utm_source=Adx_admicro&utm_campaign=cotthoaivuong&utm_medium=thoat-khoi-thoat-vi-dot-song-co-sau-2-thang&utm_content=[admdomain]',
    sologan: '',
    title: 'Thoát khỏi thoát vị đốt sống cổ sau 2 tháng',
    r: 50,
    cpa: 1,
    isview: '',
    domain: 'benhdaulung.vn',
    titlebox: 'TƯ VẤN BỆNH XƯƠNG KHỚP HAY GẶP',
    bid: 68234,
    brand: '',
    desc: 'Do công việc nặng nhọc, hai tay tôi tê nhức, cổ thì hay nằm gối cao nên mỏi dữ lắm',
    cid: 21534,
  }, {
    image: '\/\/adi.admicro.vn\/adt\/adn\/2017\/01\/e5-adx587ca1cf8f045.jpg',
    pr: 6920376445,
    color: '0059a9',
    link3rd: '',
    link: 'http:\/\/benhdaulung.vn\/bai-viet\/thong-tin-benh\/phat-hien-moi-dau-vem-xanh-chua-benh-dau-lung-hieu-qua.html?utm_source=Adx_admicro&utm_campaign=cotthoaivuong&utm_medium=dau-vem-xanh-cho-benh-dau-lung-hieu-qua&utm_content=[admdomain]',
    sologan: '',
    title: 'Phát hiện mới: Dầu vẹm xanh cho bệnh đau lưng hiệu quả',
    r: 50,
    cpa: 1,
    isview: '',
    domain: 'benhdaulung.vn',
    titlebox: 'TƯ VẤN BỆNH XƯƠNG KHỚP HAY GẶP',
    bid: 68235,
    brand: '',
    desc: 'Ở độ tuổi xế chiều, người già thường mắc những căn bệnh về xương khớp như bệnh đau lưng...',
    cid: 21534,
  }],
  cid: 10172,
  height: 300,
};
